---
# run on only items staged in git:  pre-commit
# automatically run on commit:      pre-commit install
# check all files in repo:          pre-commit run --all-files
# update all checks to latest:      pre-commit autoupdate
# https://github.com/pre-commit/pre-commit-hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ["--maxkb=150"]
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-xml
      - id: end-of-file-fixer
      # https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/
      # - id: mixed-line-ending
      #   args: ['--fix=no']
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      #  args: [--markdown-linebreak-ext=md]
      - id: detect-private-key
      # - id: no-commit-to-branch
      #   args: [--branch, main]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        args: [-c=.yamllint.yaml]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
      - id: isort
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
