---
name: black

on:
  push:
    paths:
      - "**.py"
      - "requirements.txt"
      - ".github/workflows/black.yaml"
  pull_request:
    paths:
      - "**.py"
      - "requirements.txt"
      - ".github/workflows/black.yaml"

jobs:
  black:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run black formatter checks
        # https://github.com/rickstaa/action-black
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: ". --check --diff --color"
