---
name: isort

on:
  push:
    paths:
      - "**.py"
      - "requirements.txt"
      - ".github/workflows/isort.yaml"
  pull_request:
    paths:
      - "**.py"
      - "requirements.txt"
      - ".github/workflows/isort.yaml"

jobs:
  isort:
    name: runner / isort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install isort
        run: pip install isort
      # - name: Install requirements
      #   run: pip install -r requirements.txt
      - name: Run isort
        run: isort . --check --diff
